name: aula14
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - banco
    restart: always  # Reinício automático
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  banco:
    image: mariadb
    environment:
      MARIADB_USER: myuser
      MARIADB_PASSWORD: secret
      MARIADB_DATABASE: mydatabase
      MARIADB_ROOT_PASSWORD: 12345
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
